---
title: "Week 2 workshop"
author: "Kai Lin A0240090W"
date: "2024-01-24"
output: 
  github_document:
    toc: true
    toc_depth: 2
    fig_width: 7
    fig_height: 6
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message = FALSE}
library(tidyverse)
library(lubridate)
```

```{r}
data = readRDS("../data/wk2_stocks.rds")
```


```{r}
cumu_returns = sum(data$SPY_returns)

avg_return = mean(data$SPY_returns)

sd_returns = sd(data$SPY_returns)
```

The cumulative returns of the S&P index during this period is `r round(cumu_returns * 100, 2)`%.

The average daily returns of the S&P index during this period is `r round(avg_return * 100, 2)`%.

The standard deviation of the daily returns of the S&P index during this period is `r round(sd_returns*100, 2)`%.


```{r}
plot(data$date, data$SPY_prices)


ggplot(data, aes(x = date, y = SPY_prices)) +
  geom_line()
```

```{r}
plot2 = data %>% group_by(year = year(date)) %>%
  filter(year<=2023) %>%
  summarise(year_sum = sum(SPY_returns)*100)

plot(plot2$year, plot2$year_sum)

ggplot(plot2, aes(x = year, y = year_sum)) + 
  geom_col()

```

